<?php /* Smarty version 2.6.18, created on 2014-07-21 14:43:14
         compiled from /var/customers/webs/strauchyve/derAdvokat/tpl/agb_text.tpl */ ?>
<script type="text/javascript" src="/derAdvokat/js/popup.js"></script>
<blockquote><p><strong>1. Gegenstand</strong></p>
<p>1.1.     Diese allgemeinen Gesch&auml;ftsbedingungen (AGB) regeln die Bedingungen, unter denen die unter dem Rechtsportal &bdquo;derAdvokat&ldquo;, sowie unter diesbez&uuml;glichen Subdomains und Aliases dieser Domain angebotenen Dienstleistung des Betreibers, der Kanzlei Strauch in D&uuml;sseldorf, von Nutzer in Anspruch genommen werden k&ouml;nnen. Mit der Eingabe des ihm zugesandten Passwortes, akzeptiert der Nutzer diese AGB, unabh&auml;ngig davon, welche der angebotenen Websites des Betreibers, von dem Nutzer verwendet     wird.</p>
<p>1.2.     Eine &Auml;nderung dieser AGB gilt von dem Nutzer als genehmigt, wenn der Nutzer     nicht innerhalb von vier Wochen nach Benachrichtigung &uuml;ber die &Auml;nderung     der AGB schriftlich widerspricht. Der Nutzer wird &uuml;ber eine etwaige &Auml;nderung     der AGB von dem Betreiber &uuml;ber seine zuletzt bekannt gegebene E-Mail-    Adresse informiert.</p>
<p><strong>2. Vertragsschluss</strong></p>
<p>2.1.     Dem Nutzer wird durch die &Uuml;bersendung eines Passwortes von der Kanzlei     Strauch ein Angebot zur kostenlosen Registrierung zugesandt. Ein Anspruch auf     Registrierung besteht nicht. Durch die Eingabe des Passwortes kommt zwischen     dem Nutzer und dem Betreiber ein unentgeltlicher Nutzungsvertrag zustande,     der von den Parteien jederzeit ohne Angabe von Gr&uuml;nden gek&uuml;ndigt werden     kann. Sofern auf den angebotenen Websites Nutzungsinhalte zur Verf&uuml;gung     gestellt     werden die kostenpflichtig sind, wird der Nutzer hierauf unter Angabe     des jeweiligen Nettopreises gesondert hingewiesen und muss einem     diesbez&uuml;glichen Vertragsschluss durch eine Eingabebest&auml;tigungstaste     best&auml;tigen.</p>
<p>2.2.    Der Nutzer sichert zu, dass alle bei der Registrierung erfolgten Daten     wahrheitsgem&auml;&szlig; angegeben wurden. Die &Auml;nderung seiner Daten wird der     Nutzer dem Betreiber unverz&uuml;glich anzeigen; dies gilt insbesondere f&uuml;r eine     &Auml;nderung seiner E-Mail-Adresse.</p>
<p>2.4.    Der Nutzer ist verpflichtet, sein Passwort geheim zu halten. Dem Betreiber ist     nicht gestattet, das Passwort des Nutzers an Dritte weiter zu geben.</p>
<p><strong>3. Dienstleistungen des Betreibers/&Auml;nderung der Dienste/Support</strong></p>
<p>3.1.    Der Betreiber bietet den registrierten Nutzern meistenteils kostenlose     Rechtsinformationen. Hierbei handelt es sich nicht um eine Rechtsberatung. Der     Betreiber &uuml;bernimmt keinerlei Gew&auml;hr f&uuml;r die Aktualit&auml;t, Korrektheit,     Vollst&auml;ndigkeit oder Qualit&auml;t der bereitgestellten Informationen.</p>
<p>3.2.    Das Angebot des Betreibers wird laufend weiterentwickelt und angepasst.     Vorhandene Funktionen oder Inhalte k&ouml;nnen daher ver&auml;ndert oder ganz     entfernt werden. Neue Funktionen oder Inhalte k&ouml;nnen hinzugef&uuml;gt werden.</p>
<p>3.3.    Der Nutzer ist durch die kostenlose Registrierung nicht berechtigt, auf s&auml;mtliche     Inhalte und Daten des Rechtsportals &bdquo;derAdvokat&ldquo; zuzugreifen. Der Betreiber     beh&auml;lt sich insbesondere vor, Inhalte zu sperren oder nur entgeltlich zur     Verf&uuml;gung zu stellen.</p>
<p><strong>4. Haftung des Betreibers</strong></p>
<p>4.1.     Haftungsanspr&uuml;che gegen den Betreiber, welche sich auf Sch&auml;den materieller     oder ideeller Art beziehen, die durch die Nutzung oder Nichtnutzung der     dargebotenen Informationen verursacht wurden, sind grunds&auml;tzlich     ausgeschlossen, sofern seitens des Betreibers kein nachweislich vors&auml;tzliches     oder grob fahrl&auml;ssiges Verschulden vorliegt. </p>
<p>4.2.    Der Betreiber &uuml;bernimmt keine Haftung f&uuml;r Ausf&auml;lle des Systems oder sonstiger     Beeintr&auml;chtigung. Dies gilt insbesondere f&uuml;r den Verlust f&uuml;r Daten w&auml;hrend einer     Eingabe.<br />
    <br />
  4.3.     Bei direkten oder indirekten Verweisen auf fremde Webseiten, &uuml;bernimmt der     Betreiber trotz sorgf&auml;ltiger inhaltlicher Kontrolle keine Haftung f&uuml;r den Inhalt     dieser Seiten. F&uuml;r den Inhalt der verlinkten Seiten sind ausschlie&szlig;lich deren     Betreiber verantwortlich.</p>
<p>4.4.     Eine Haftung des Betreibers f&uuml;r Sch&auml;den an dem Computersystem des     Nutzers, ist auf Vorsatz oder grobe Fahrl&auml;ssigkeit beschr&auml;nkt.</p>
<p><strong>5. Daten/Cookies/Google</strong></p>
<p>5.1. Die Daten des Nutzers k&ouml;nnen nicht von Dritten eingesehen werden. Im     Zusammenhang mit dem Umfang und der Verarbeitung dieser Daten wird auf     die <a href="/derAdvokat/agb" onclick="popup()"><font color="blue">Datenschutzerkl&auml;rung</font></a> verwiesen.</p>
<p>5.2.    Sowohl der Betreiber, als auch andere Unternehmen (Suchmaschinen wie z. B.     Google Analytics) verwenden f&uuml;r die automatische Autorisation oder zur     Analyse des Benutzerverhaltens sogenannte Cookies (kleine Textdateien, die     dem Austausch von Informationen zwischen Computerprogrammen dienen).     Soweit der Nutzer eine Speicherung von Cookies auf seinem Computer nicht     w&uuml;nscht, ist er gehalten, diese durch entsprechende Einstellungen auf seinem     Computer zu unterdr&uuml;cken.</p>
<p><strong>6. Pflichten des Nutzers</strong></p>
<p>6.1.    Der Nutzer ist verpflichtet daf&uuml;r Sorge zu tragen, dass die von ihm eingestellten     Inhalte frei von Viren, W&uuml;rmern, Trojanern oder sonstigen schadhaften     Programmen sind, die die Funktionsf&auml;higkeit der Internetseiten des Betreibers     beeintr&auml;chtigen k&ouml;nnten.</p>
<p>6.2.     Soweit der Zugriff auf die Inhalte des Rechtsportals &bdquo;derAdvokat&ldquo; nur mit Hilfe     des Passwortes m&ouml;glich ist, ist es dem Benutzer untersagt, Dritten die dort     befindlichen Inhalte zur Verf&uuml;gung zu stellen oder Dritten eine     Zugangsm&ouml;glichkeit einzur&auml;umen. <br />
</p>
<p><strong>7. Beendigung des Vertrages</strong></p>
<p>7.1.     Jede Partei ist berechtigt, das Vertragsverh&auml;ltnis jederzeit und ohne Einhaltung     einer Frist oder Angabe eines Grundes zu beenden.</p>
<p>7.2.     Nach Beendigung des Vertrages ist es dem Nutzer nicht mehr gestattet, auf das     Rechtsportal &bdquo;derAdvokat&ldquo; zuzugreifen, sofern auf die diesbez&uuml;glichen Inhalte     nur durch Eingabe eines Passwortes zugegriffen werden kann. Auch nach     Beendigung des Vertrages ist der Nutzer nicht berechtigt, die entsprechenden     Inhalte des Rechtsportals an Dritte weiterzugeben.</p>
<p><strong>8. Schlussbestimmungen</strong></p>
<p>8.1.     F&uuml;r das Vertragsverh&auml;ltnis zwischen dem Nutzer und dem Betreiber gilt das     Recht der Bundesrepublik Deutschland, unter Ausschluss des UN-Kaufrechts.</p>
<p>8.2.     Marken- und sonstige Schutzrechte des Betreibers d&uuml;rfen au&szlig;erhalb der Seiten des     Rechtsportals &bdquo;derAdvokat&ldquo; nur nach vorheriger Genehmigung durch den     Betreiber verwendet werden.</p>
<p>8.3.     Sollten einzelne Bestimmungen dieser AGB unwirksam sein oder werden,     bleiben     die &uuml;brigen Bestimmungen hiervon unber&uuml;hrt.</p>
<p>Stand 28.09.2009<br />
    <br />
</p></blockquote>